#include "assertive.h"
#include <algorithm>
#include <limits.h>
#include <stdint.h>
#include <stdarg.h>
#include <string.h>
#include <malloc.h>
#include <wchar.h>
#include <stdio.h>
#include <new>
#define WIN32_LEAN_AND_MEAN        // Exclude rarely-used stuff from Windows headers
#define NOMINMAX
#include <windows.h>
#include <vfw.h>
#include "ss.h"
#include <string>
#include "VSScript.h"
#include "vsfspfm.h"
#include "vsfs.h"
