name: Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        include:
        - arch: x86_64
          runs-on: ubuntu-latest
        - arch: aarch64
          runs-on: ubuntu-24.04-arm
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v6

    - uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_BUILD: cp312-*
        CIBW_BEFORE_ALL: >
          git clone https://github.com/sekrit-twc/zimg.git --depth 1 --recurse-submodules --shallow-submodules &&
          cd zimg &&
          ./autogen.sh &&
          ./configure --disable-shared --with-pic &&
          make -j$(nproc) &&
          make install -j$(nproc) &&
          cd .. &&
          rm -rf zimg
      with:
        output-dir: dist

    - name: Check for abi3 violations or inconsistencies
      run: |
        pipx run abi3audit --verbose dist/*.whl

    - uses: actions/upload-artifact@v7
      with:
        name: vapoursynth-manylinux_${{ matrix.arch }}
        path: dist/*manylinux*.whl

    - uses: actions/upload-artifact@v7
      with:
        name: vapoursynth-musllinux_${{ matrix.arch }}
        path: dist/*musllinux*.whl

    - name: Install wheel and run test in base environment
      run: |
        pip install vapoursynth --no-index --find-links dist
        vsscript-config
        which vspipe
        vspipe --version
        python -m unittest discover -s test -p "*test.py"
        pip uninstall -y vapoursynth

    - name: Install wheel and run test in virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install vapoursynth --no-index --find-links dist
        which vspipe
        vspipe --version
        python -m unittest discover -s test -p "*test.py"

  publish:
    permissions:
      id-token: write
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/R') && !contains(github.ref, 'RC') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v8
      with:
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
