name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build-wheel:
    strategy:
      matrix:
        include:
        - arch: x86_64
          runs-on: macos-15-intel
        - arch: arm64
          runs-on: macos-15

    runs-on: ${{ matrix.runs-on }}

    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14

    steps:
    - uses: actions/checkout@v6

    - name: Install Homebrew packages
      run: |
        brew update
        brew install automake libtool

    - name: Set environment variables
      run: |
        echo "nproc=$(sysctl -n hw.logicalcpu)" >> $GITHUB_ENV

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg.git --depth 1 --recurse-submodules --shallow-submodules
        pushd zimg
        ./autogen.sh
        ./configure
        make -j${{ env.nproc }}
        sudo make install -j${{ env.nproc }}
        popd
        rm -rf zimg

    - name: Build sdist
      run: |
        pipx run build --sdist

    - uses: pypa/cibuildwheel@v3.4.0
      with:
        output-dir: dist

    - uses: actions/upload-artifact@v7
      with:
        name: vapoursynth-sdist
        path: dist/*.tar.gz
        overwrite: true

    - uses: actions/upload-artifact@v7
      with:
        name: vapoursynth-macosx_${{ matrix.arch }}
        path: dist/*.whl
