name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        include:
        - arch: x86_64
          runs-on: macos-26-intel
        - arch: arm64
          runs-on: macos-26
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    env:
      MACOSX_DEPLOYMENT_TARGET: 13.3

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install Homebrew packages
      run: |
        brew install automake libtool

    - name: Install Python packages
      run: |
        pip install -U abi3audit build

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg.git --depth 1 --recurse-submodules --shallow-submodules
        pushd zimg
        ./autogen.sh
        ./configure --disable-shared --with-pic
        make -j3
        sudo make install -j3
        popd
        rm -rf zimg

    - name: Build
      run: |
        python -m build --wheel

    - name: Check for abi3 violations or inconsistencies
      run: |
        abi3audit --verbose dist/*.whl

    - uses: actions/upload-artifact@v7
      with:
        name: vapoursynth-macosx_${{ matrix.arch }}
        path: dist/*.whl

    - name: Install wheel and run test in base environment
      run: |
        pip install vapoursynth --no-index --find-links dist
        vapoursynth-config
        which vspipe
        vspipe --version
        python -m unittest discover -s test -p "*test.py"
        pip uninstall -y vapoursynth

    - name: Install wheel and run test in virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install vapoursynth --no-index --find-links dist
        which vspipe
        vspipe --version
        python -m unittest discover -s test -p "*test.py"

  publish:
    permissions:
      id-token: write
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/R') && !contains(github.ref, 'RC') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v8
      with:
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
