name: Windows

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install Python packages
      run: |
        pip install -U abi3audit build wheel

    - name: Build
      run: |
        python -m build -Csetup-args="--vsenv"
        pushd dist
        Get-ChildItem *.whl | ForEach-Object { wheel tags --remove --python-tag cp312 $_.Name }
        popd

    - name: Check for abi3 violations or inconsistencies
      run: |
        abi3audit --verbose dist/*.whl

    - uses: actions/upload-artifact@v7
      with:
        name: vapoursynth-sdist
        path: dist/*.tar.gz

    - uses: actions/upload-artifact@v7
      with:
        name: vapoursynth-win_amd64
        path: dist/*.whl

    - name: Install wheel and run test in base environment
      run: |
        pip install vapoursynth --no-index --find-links dist
        vapoursynth-config
        where.exe vspipe
        vspipe --version
        python -m unittest discover -s test -p "*test.py"
        pip uninstall -y vapoursynth

    - name: Install wheel and run test in virtual environment
      run: |
        python -m venv .venv
        .venv/Scripts/Activate.ps1
        pip install vapoursynth --no-index --find-links dist
        where.exe vspipe
        vspipe --version
        python -m unittest discover -s test -p "*test.py"

  publish:
    permissions:
      id-token: write
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/R') && !contains(github.ref, 'RC') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v8
      with:
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
